server:
  port: ${port:8099}

spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql 的数据库驱动类名称
    url: jdbc:mysql://localhost:3306/u-live?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT&autoReconnect=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  redis:
    host: 47.98.XXX.XXX
    port: 6397
    database: 1
    password: 123456
  data:
    mongodb:
      uri: mongodb://root:root@47.98.XXX.XXX:27017
      database: u-live-dev
  rabbitmq:
    host: 47.98.XXX.XXX
    port: 5672
    username: admin
    password: admin
    virtual-host: u-live
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.XXX.XXX:8848   # nacos 所在的地址
#        counts: 1
# 打开监控
management:
  endpoint:
    web:
      exposure:
        include: '*'

# MinIO 配置
minio:
  endpoint: http://47.98.XXX.XXX:9000/      # MinIO服务地址
  fileHost: http://47.98.XXX.XXX:9000/      # 文件地址host
  bucketName: u-live                      # 存储桶bucket名称
  accessKey: tanz                         # 用户名
  secretKey: tanz123456                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m