server:
#  port: 8099
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  application:
    name: u-live-nacos
  profiles:
    active: prod
  banner:
    location: classpath:banner/banner.txt
  servlet:
    multipart:
    max-file-size: 2MB
    max-request-size: 2MB
  main:
    allow-circular-references: true  #??????
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  type-aliases-package: com.tanz.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.tanz.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true

logging:
  level:
    root: info